# Generated by Django 5.0.1 on 2024-02-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="書籍名")),
                (
                    "publish",
                    models.CharField(blank=True, max_length=100, verbose_name="出版社"),
                ),
                (
                    "page",
                    models.IntegerField(blank=True, default=0, verbose_name="ページ数"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField(default=0, verbose_name="星")),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="MyApp0.book",
                        verbose_name="書籍",
                    ),
                ),
            ],
        ),
    ]
