# Generated by Django 5.0.6 on 2025-04-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nikirunscore",
            name="not_play_yet",
            field=models.BooleanField(default=False),
        ),
    ]
