# Generated by Django 5.0.6 on 2025-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_nikirunscore_not_play_yet"),
    ]

    operations = [
        migrations.AddField(
            model_name="nikirunscore",
            name="character",
            field=models.CharField(default="PigMan", max_length=16),
        ),
    ]
