# Generated by Django 5.0.6 on 2025-05-10 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_remove_nikirunscore_user_nikirun_delete_nikiruninfo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="nikirun",
            old_name="character",
            new_name="character_last",
        ),
        migrations.RenameField(
            model_name="nikirun",
            old_name="score_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="nikirun",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="nikirun",
            name="not_play_yet",
        ),
        migrations.RemoveField(
            model_name="nikirun",
            name="score",
        ),
        migrations.RemoveField(
            model_name="nikirun",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="nikirun",
            name="bronze_coin",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.CreateModel(
            name="NIKIRunScore",
            fields=[
                (
                    "score_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("score", models.FloatField()),
                ("play_yet", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("character", models.CharField(default="PigMan", max_length=16)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
