# Generated by Django 5.0.6 on 2025-05-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_rename_character_nikirun_character_last_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nikirunscore",
            name="play_yet",
        ),
        migrations.AlterField(
            model_name="nikirunscore",
            name="score",
            field=models.FloatField(default=None, null=True),
        ),
    ]
