# Generated by Django 5.0.6 on 2025-05-10 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_remove_nikirunscore_play_yet_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NIKIRun",
            new_name="NIKIRunUserInfo",
        ),
    ]
