# Generated by Django 5.0.6 on 2025-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_rename_nikirun_nikirunuserinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nikirunscore",
            old_name="score_id",
            new_name="id",
        ),
    ]
