# Generated by Django 5.0.6 on 2025-07-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_score_id_nikirunscore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikirunuserinfo',
            name='options',
            field=models.JSONField(default={'bgmVolume': 1.0, 'fullscreen': False, 'masterVolume': 1.0, 'sfxVolume': 1.0}),
        ),
        migrations.AlterField(
            model_name='nikirunscore',
            name='character',
            field=models.CharField(default='Pigger', max_length=16),
        ),
        migrations.AlterField(
            model_name='nikirunuserinfo',
            name='character_last',
            field=models.CharField(default='Pigger', max_length=16),
        ),
    ]
