# Generated by Django 5.0.6 on 2025-07-24 09:16

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_nikirunuserinfo_options_alter_nikirunscore_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nikirunuserinfo',
            name='options',
            field=models.JSONField(default=games.models.default_game_options),
        ),
    ]
