# Generated by Django 5.0.6 on 2025-07-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_nikirunuserinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nikirunuserinfo',
            name='options',
        ),
    ]
