# Generated by Django 5.0.6 on 2025-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_nikirunuserinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikirunuserinfo',
            name='equipments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
