# Generated by Django 5.0.6 on 2025-03-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_emailaddress_unique_primary_email"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomEmailAddress",
            fields=[
                (
                    "emailaddress_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.emailaddress",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            bases=("account.emailaddress",),
        ),
    ]
