# Generated by Django 5.0.6 on 2025-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(
                choices=[
                    ("accounts/img/user_icons/user_icon_1.png", "User Image1"),
                    ("accounts/img/user_icons/user_icon_2.png", "User Image2"),
                    ("accounts/img/user_icons/user_icon_3.png", "User Image3"),
                ],
                default="accounts/img/user_icons/user_icon_1.png",
                max_length=100,
                verbose_name="アイコン",
            ),
        ),
    ]
