# Generated by Django 5.0.6 on 2024-12-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(
                choices=[
                    ("accounts/img/user_icons/user_icon_default_man.png", "User Image1")
                ],
                default="accounts/img/user_icons/user_icon_default_man.png",
                max_length=100,
                verbose_name="アイコン",
            ),
        ),
    ]
