# Generated by Django 5.0.6 on 2025-03-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customemailaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomEmailAddress",
        ),
    ]
