# Generated by Django 5.0.6 on 2025-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_customemailaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(
                choices=[
                    ("user_icon_1.png", "User Image1"),
                    ("user_icon_2.png", "User Image2"),
                    ("user_icon_3.png", "User Image3"),
                    ("user_icon_4.png", "User Image4"),
                    ("user_icon_5.png", "User Image5"),
                ],
                default="user_icon_1.png",
                max_length=100,
                verbose_name="アイコン",
            ),
        ),
    ]
