# Generated by Django 5.0.6 on 2025-02-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(
                choices=[
                    ("/static/accounts/img/user_icons/user_icon_1.png", "User Image1"),
                    ("/static/accounts/img/user_icons/user_icon_2.png", "User Image2"),
                    ("/static/accounts/img/user_icons/user_icon_3.png", "User Image3"),
                    ("/static/accounts/img/user_icons/user_icon_4.png", "User Image4"),
                    ("/static/accounts/img/user_icons/user_icon_5.png", "User Image5"),
                ],
                default="/static/accounts/img/user_icons/user_icon_1.png",
                max_length=100,
                verbose_name="アイコン",
            ),
        ),
    ]
