# Generated by Django 5.0.1 on 2024-02-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=128, null=True, verbose_name="password"
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "date_last_login",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="last login date"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="is admin"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="address"
                    ),
                ),
                (
                    "place_favorite",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="favorite place"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True, verbose_name="diary date")),
                (
                    "name_place",
                    models.CharField(
                        max_length=128, null=True, verbose_name="place name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "date_last_updated",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="last updated date"
                    ),
                ),
                (
                    "is_publish",
                    models.BooleanField(default=False, verbose_name="is publish"),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "datetime",
                    models.DateTimeField(blank=True, verbose_name="time detail"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diary.user"
                    ),
                ),
            ],
        ),
    ]
