# Generated by Django 5.0.6 on 2024-12-26 14:39

import diary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "coin_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("num", models.IntegerField(default=0)),
                ("num_continue", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "diary_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateField(null=True, verbose_name="日記の日時")),
                (
                    "date_created",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="作成日"
                    ),
                ),
                (
                    "date_last_updated",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="最終更新日"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "rank",
                    models.IntegerField(
                        choices=[(0, "Gold"), (1, "Normal")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="市区町村"
                    ),
                ),
                (
                    "display",
                    models.CharField(blank=True, max_length=128, verbose_name="表示名"),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=128, verbose_name="ラベル"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="locations/",
                        verbose_name="サイクリング画像",
                    ),
                ),
                ("image_hash", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "is_home",
                    models.BooleanField(default=False, verbose_name="登録地域か否か"),
                ),
                (
                    "is_thumbnail",
                    models.BooleanField(default=False, verbose_name="サムネイル"),
                ),
                (
                    "diary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="diary.diary",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TempImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                ("image", models.ImageField(upload_to=diary.models.upload_to)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                (
                    "date_photographed",
                    models.DateTimeField(null=True, verbose_name="撮影日時"),
                ),
                (
                    "date_lastModified",
                    models.DateTimeField(null=True, verbose_name="ファイル更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="diary_date_unique"
            ),
        ),
    ]
