# Generated by Django 5.0.1 on 2024-02-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="creation_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
