# Generated by Django 5.0.6 on 2025-02-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="公開設定"),
        ),
    ]
