# Generated by Django 5.0.1 on 2024-02-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=0, max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
    ]
