# Generated by Django 5.0.6 on 2025-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="date_list",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="coin",
            name="timestamp",
            field=models.DateField(null=True),
        ),
    ]
