# Generated by Django 5.0.6 on 2025-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_coin_date_list_alter_coin_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lon",
            field=models.FloatField(blank=True),
        ),
    ]
