# Generated by Django 5.0.1 on 2024-02-10 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_diary_creation_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="name",
        ),
    ]
