# Generated by Django 5.0.6 on 2025-02-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_good"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempimage",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tempimage",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
