# Generated by Django 5.0.1 on 2024-03-22 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_alter_user_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
