# Generated by Django 5.0.6 on 2025-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_alter_tempimage_lat_alter_tempimage_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="rotate_angle",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="角度"
            ),
        ),
    ]
