# Generated by Django 5.0.1 on 2024-02-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_rename_username_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="place",
            field=models.CharField(default="tmp field", max_length=256),
        ),
    ]
