# Generated by Django 5.0.1 on 2024-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="place_favorite",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
