# Generated by Django 5.0.1 on 2024-02-11 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_diary_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="place",
        ),
    ]
