# Generated by Django 5.0.1 on 2024-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_remove_user_address_remove_user_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=256, verbose_name="address"),
        ),
        migrations.AddField(
            model_name="user",
            name="place_favorite",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="favorite place"
            ),
        ),
    ]
