# Generated by Django 5.0.1 on 2024-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_diary_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="content",
        ),
        migrations.AddField(
            model_name="diary",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
