# Generated by Django 5.0.1 on 2024-03-23 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_remove_user_first_name_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="CycleDiary_User",
        ),
    ]
