# Generated by Django 5.0.1 on 2024-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0007_remove_diary_content_diary_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="creation_date",
            field=models.DateField(null=True, verbose_name="creation date"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_date",
            field=models.DateField(null=True, verbose_name="last login date"),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True, verbose_name="password"),
        ),
    ]
