# Generated by Django 5.0.1 on 2024-03-23 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0007_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
    ]
