# Generated by Django 5.0.1 on 2024-02-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0008_user_creation_date_user_last_login_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="creation_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
