# Generated by Django 5.0.1 on 2024-03-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0009_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
