# Generated by Django 5.0.1 on 2024-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0010_user_creation_date_user_last_login_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_date",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="last login date"
            ),
        ),
    ]
