# Generated by Django 5.0.4 on 2024-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0010_user_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("state", models.CharField(max_length=128)),
                ("display", models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="place_favorite",
        ),
        migrations.AddField(
            model_name="diary",
            name="locations",
            field=models.ManyToManyField(blank=True, to="diary.location"),
        ),
        migrations.AddField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(blank=True, to="diary.location"),
        ),
    ]
