# Generated by Django 5.0.1 on 2024-02-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0011_alter_user_creation_date_alter_user_last_login_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="last_updated_date",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="last updated date"
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="creation_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="creation date"
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="place",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
