# Generated by Django 5.0.4 on 2024-05-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0011_location_remove_user_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diary.location",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users_locations",
                to="diary.location",
            ),
        ),
    ]
