# Generated by Django 5.0.4 on 2024-05-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0012_user_home_alter_user_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="users_locations", to="diary.location"
            ),
        ),
    ]
