# Generated by Django 5.0.1 on 2024-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0012_diary_last_updated_date_alter_diary_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
