# Generated by Django 5.0.4 on 2024-05-06 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0014_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
    ]
