# Generated by Django 5.0.4 on 2024-05-06 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0015_remove_user_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home",
        ),
        migrations.RemoveField(
            model_name="user",
            name="locations",
        ),
        migrations.AddField(
            model_name="location",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
