# Generated by Django 5.0.4 on 2024-05-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0016_remove_user_home_remove_user_locations_location_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="diary.location",
            ),
            preserve_default=False,
        ),
    ]
