# Generated by Django 5.0.4 on 2024-05-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0017_remove_location_user_user_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diary.location",
            ),
        ),
    ]
