# Generated by Django 5.0.4 on 2024-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0018_alter_user_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="display",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="location",
            name="state",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
