# Generated by Django 5.0.4 on 2024-05-17 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0019_alter_location_display_alter_location_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="home",
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="diary.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("diary.location",),
        ),
    ]
