# Generated by Django 5.0.4 on 2024-05-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0020_remove_user_home_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diary.location",
            ),
        ),
        migrations.DeleteModel(
            name="Home",
        ),
    ]
