# Generated by Django 5.0.6 on 2024-07-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0021_user_home_delete_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="name_place",
        ),
    ]
