# Generated by Django 5.0.6 on 2024-08-08 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='locations',
        ),
        migrations.AddField(
            model_name='diary',
            name='locations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diary.location'),
            preserve_default=False,
        ),
    ]
