# Generated by Django 5.0.6 on 2024-08-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0024_remove_diary_locations_diary_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='locations',
        ),
        migrations.AddField(
            model_name='diary',
            name='locations',
            field=models.ManyToManyField(blank=True, to='diary.location'),
        ),
    ]
