# Generated by Django 5.0.6 on 2024-08-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0025_remove_diary_locations_diary_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='datetime',
        ),
    ]
