# Generated by Django 5.0.6 on 2024-08-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0027_remove_diary_image_remove_diary_is_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(null=True, verbose_name='日記の日時'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date_last_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='最終更新日'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='locations',
            field=models.ManyToManyField(blank=True, to='diary.location', verbose_name='場所情報'),
        ),
        migrations.AlterField(
            model_name='location',
            name='display',
            field=models.CharField(blank=True, max_length=128, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=128, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.location', verbose_name='お気に入りの場所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='アイコン'),
        ),
    ]
