# Generated by Django 5.0.6 on 2024-08-08 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0028_remove_location_image_alter_diary_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.diary'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
