# Generated by Django 5.0.6 on 2024-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0029_remove_diary_locations_location_diary_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="name_place",
            field=models.CharField(
                max_length=128, null=True, verbose_name="place name"
            ),
        ),
    ]
