# Generated by Django 5.0.6 on 2024-08-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0030_diary_name_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="name_place",
        ),
    ]
