# Generated by Django 5.0.6 on 2024-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0031_remove_diary_name_place"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="diary_date_unique"
            ),
        ),
    ]
