# Generated by Django 5.0.6 on 2024-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0032_diary_diary_date_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="diary",
        ),
        migrations.AddField(
            model_name="diary",
            name="locations",
            field=models.ManyToManyField(
                related_name="diaries", to="diary.location", verbose_name="場所情報"
            ),
        ),
    ]
