# Generated by Django 5.0.6 on 2024-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0033_remove_location_diary_diary_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_home",
            field=models.BooleanField(default=False, verbose_name="登録地域か否か"),
        ),
    ]
