# Generated by Django 5.0.6 on 2024-08-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0034_location_is_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diary",
            name="locations",
        ),
        migrations.AddField(
            model_name="location",
            name="diary",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="diary.diary"
            ),
        ),
    ]
