# Generated by Django 5.0.6 on 2024-08-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0035_remove_diary_locations_location_diary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="diary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diaries",
                to="diary.diary",
            ),
        ),
    ]
