# Generated by Django 5.0.6 on 2024-08-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0037_alter_location_diary"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="label",
            field=models.CharField(blank=True, max_length=128, verbose_name="ラベル"),
        ),
    ]
