# Generated by Django 5.0.6 on 2024-09-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0039_alter_diary_id_alter_location_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(null=True, unique=True, verbose_name='日記の日時'),
        ),
    ]
