# Generated by Django 5.0.6 on 2024-09-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0040_alter_diary_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(null=True, verbose_name="日記の日時"),
        ),
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images",
                verbose_name="サイクリング画像",
            ),
        ),
    ]
