# Generated by Django 5.0.6 on 2024-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0041_alter_diary_date_alter_location_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(null=True, unique=True, verbose_name="日記の日時"),
        ),
    ]
