# Generated by Django 5.0.6 on 2024-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0042_alter_diary_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="locations/",
                verbose_name="サイクリング画像",
            ),
        ),
    ]
