# Generated by Django 5.0.6 on 2024-09-11 11:49

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0044_alter_location_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=diary.models.upload_to,
                verbose_name="サイクリング画像",
            ),
        ),
    ]
