# Generated by Django 5.0.6 on 2024-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0045_alter_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
