# Generated by Django 5.0.6 on 2024-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0046_location_image_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="image_hash",
        ),
    ]
