# Generated by Django 5.0.6 on 2024-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0047_remove_location_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_thumbnail",
            field=models.BooleanField(default=False, verbose_name="サムネイル"),
        ),
    ]
