# Generated by Django 5.0.6 on 2024-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0048_location_is_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
