# Generated by Django 5.0.6 on 2024-09-23 12:53

import diary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0049_location_image_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="locations/",
                verbose_name="サイクリング画像",
            ),
        ),
        migrations.CreateModel(
            name="TempImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to=diary.models.upload_to)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
