# Generated by Django 5.0.6 on 2024-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0050_alter_location_image_tempimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempimage",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="作成日"),
        ),
    ]
