# Generated by Django 5.0.6 on 2024-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0051_tempimage_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempimage",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="作成日時"
            ),
        ),
    ]
