# Generated by Django 5.0.6 on 2024-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0052_alter_tempimage_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempimage",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tempimage",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="tempimage",
            name="lon",
            field=models.FloatField(null=True),
        ),
    ]
