# Generated by Django 5.0.6 on 2024-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0053_tempimage_date_tempimage_lat_tempimage_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempimage",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
