# Generated by Django 5.0.6 on 2024-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0054_alter_tempimage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempimage",
            name="date",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
