# Generated by Django 5.0.6 on 2024-10-12 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0055_alter_tempimage_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="id",
            new_name="location_id",
        ),
    ]
