# Generated by Django 5.0.6 on 2024-10-12 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0056_rename_id_location_location_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diary",
            old_name="id",
            new_name="diary_id",
        ),
    ]
