# Generated by Django 5.0.6 on 2024-10-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0057_rename_id_diary_diary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempimage",
            name="date_lastModified",
            field=models.DateTimeField(null=True, verbose_name="ファイル更新日時"),
        ),
    ]
