# Generated by Django 5.0.6 on 2024-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0058_tempimage_date_lastmodified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempimage",
            name="date",
        ),
        migrations.AddField(
            model_name="tempimage",
            name="date_photographed",
            field=models.DateTimeField(null=True, verbose_name="撮影日時"),
        ),
    ]
