# Generated by Django 5.0.6 on 2024-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0059_remove_tempimage_date_tempimage_date_photographed"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="rank",
            field=models.IntegerField(choices=[(0, "Gold"), (1, "Normal")], default=1),
        ),
    ]
