# Generated by Django 5.0.6 on 2024-10-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0061_coin_user_coin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
