# Generated by Django 5.0.6 on 2024-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0062_alter_coin_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="coin",
            name="num_continue",
            field=models.IntegerField(default=0),
        ),
    ]
