# Generated by Django 5.0.6 on 2024-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0063_coin_num_continue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(null=True, verbose_name="日記の日時"),
        ),
    ]
