# Generated by Django 5.0.6 on 2024-11-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0065_alter_user_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.CharField(
                choices=[
                    ("diary/img/user_icons/user_icon_default_man.png", "User Image1")
                ],
                default="diary/img/user_icons/user_icon_default_man.png",
                max_length=100,
                verbose_name="アイコン",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=8, unique=True, verbose_name="ユーザー名"
            ),
        ),
    ]
